import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Solution {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        List<String> outputs = new ArrayList<>();
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_RIGHT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");      outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");
        outputs.add("TURN_LEFT");
        outputs.add("MOVE_FORWARD");

        while (true) {
            System.out.println(outputs.remove(0));
        }
    }
}
